Gas Consumption Supply Crud
NNPC-NGML/gas-consumption-supply pull request #1
Opened 2024-09-23 03:43 UTC by shadowalker001

Gas Consumption Supply Crud

2024-09-23 12:12 UTC, kingsonly requested changes

2024-09-23 12:12 UTC, kingsonly commented on database/migrations/2024_09_22_192745_create_daily_volumes_table.php
> +            $table->float('amount')->comment('amount from (volume * rate) in NGN');
remove the amount and rate

2024-09-23 12:12 UTC, kingsonly commented on app/Services/DailyVolumeService.php
> +            } elseif ($key === 'updated_at_from') {
this would have been better as a switch case

2024-09-23 12:12 UTC, kingsonly commented on app/Services/DailyVolumeService.php
> +        return DailyVolume::all();
this should be paginated

2024-09-23 12:12 UTC, kingsonly commented on app/Services/DailyVolumeService.php
> +                // Decode the JSON data
add transaction to this

2024-09-23 12:12 UTC, kingsonly commented on app/Http/Controllers/DailyVolumeController.php
> +            return DailyVolumeResource::collection($dailyVolumes)->additional([
this should be paginated

2024-09-23 12:12 UTC, kingsonly commented on app/Http/Controllers/DailyVolumeController.php
> +            return DailyVolumeResource::collection($dailyVolumes)->additional([
the default should be query for the current month

2024-09-23 12:12 UTC, kingsonly commented on app/Http/Controllers/DailyVolumeController.php
> +        } catch (\Illuminate\Database\Eloquent\ModelNotFoundException $e) {
delete follows the same approach as always, but we need to think about the approach for delete

2024-10-10 20:22 UTC, Skillz-systems approved these changes

2024-10-10 20:23 UTC, merged